# Generated by Django 4.0.1 on 2022-02-23 01:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0002_homepost_post_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepost',
            name='post_likes',
            field=models.ManyToManyField(related_name='Blog_Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
