# Generated by Django 4.0.1 on 2022-02-23 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_homepost_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepost',
            name='post_likes',
        ),
        migrations.RemoveField(
            model_name='homepost',
            name='post_link',
        ),
    ]
